// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGamePlayTags
{
	/**Input tags**/
	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);



	/**Player tags**/
	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);



	/** Enemy tags **/
	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

	/** Shared tags **/
	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);

	ARPGPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);

}
